export const CHARACTER_LIST = {
    LETTER: "letter",
    DIGIT: "digit",
    ASTERISK: "*",
    PLUS: "+",
    SLASH: "/",
    HYPHEN: "-",
    UNDERSCORE: "_",
    DOT: ".",
    WHITE_SPACE: " ",
    START_PAREN: "(",
    END_PAREN: ")",
    START_BRACKET: "[",
    END_BRACKET: "]",
    EQUALS: "=",
    GREATER_THAN: ">",
    DOUBLE_QUOTE: "\"",
    BACKTICK: "`",
    PERCENTAGE:"%", 
    AT: "@",
    SEMICOLON: ";",
    AMPERSAND: "&",
    VERTICAL_BAR: "|",
    EXCLAMATION_MARK: "!", // Está en sueco xD, debo ponerle EXCLAMATION_MARK
    LINE_BREAK: "\n"
};