export const CHARACTER_LIST = {
    LETTER: "letter",
    DIGIT: "digit",
    ASTERISK: "*",
    PLUS: "+",
    SLASH: "/",
    HYPHEN: "-",
    UNDERSCORE: "_",
    DOT: ".",
    WHITE_SPACE: " ",
    START_PAREN: "(",
    END_PAREN: ")",
    START_BRACKET: "[",
    END_BRACKET: "]",
    SEMICOLON: ";",
    AMPERSAND: "&",
    VERTICAL_BAR: "|",
    UTROPSTECKEN: "!",
    LINE_BREAK: "\n"
};