export const STATES = {
    START: "start",
    INTEGER: "integer",
    DECIMAL: "decimal",
    IDENTIFIER: "identifier",
    OPERATOR_PLUS: "operatorPlus",
    OPERATOR_SUBTRACTION: "operatorSubtraction",
    OPERATOR_DIVISION: "operatorDivision",
    OPERATOR_PRODUCT: "operatorProduct",
    OPERATOR_POWER: "operatorPower",
    OPERATOR_MODULE: "operatorModule",
    START_PAREN: "startParen",
    END_PAREN: "endParen",
    START_CURLY_BRACE: "startCurlyBrace",
    END_CURLY_BRACE: "endCurlyBrace",
    OPERATOR_CONJ_1: "operatorConj1",
    OPERATOR_CONJ_F: "operatorConjF",
    OPERATOR_DISJ_1: "operatorDisj1",
    OPERATOR_DISJ_F: "operatorDisjF",
    OPERATOR_NOT: "operatorNot",
    DECREMENTOR_VAR_1_1: "decrementorVar11",
    DECREMENTOR_VAR: "decrementorVar",
    MULTIPLIER_VAR: "multiplierVar",
    DIVISOR_VAR: "divisorVar",
    POWER_VAR: "powerVar",
    OPERATOR_TERNARY_TRUE: "operatorTernaryTrue",
    OPERATOR_TERNARY_FALSE: "operatorTernaryFalse",
    OPERATOR_GREATER_THAN: "operatorGreaterThan",
    OPERATOR_GREATER_THAN_OR_EQUAL_TO: "operatorGreaterThanOrEqualTo",
    OPERATOR_LESS_THAN: "operatorLessThan",
    OPERATOR_LESS_THAN_OR_EQUAL_TO: "operatorLessThanOrEqualTo",
    OPERATOR_EQUALS_1: "operatorEquals1",
    OPERATOR_EQUALS_F: "operatorEqualsF",
    OPERATOR_DIFFERENT: "operatorDifferent",
    END_PAREN: "endParen",
    STRING_1: "string1",
    STRING_INTERP_1: "stringInterpolation1",
    STRING_INTERP_2: "stringInterpolation2",
    SEPARATION_OF_EXPRESSIONS: "separationOfExpressions",
    STRING_F: "stringF",
    EOF: "end",
    RESERVED_WORD: "reservedWord",
    ERROR: "error",
    OPERATOR_ASSIGNMENT_1: "operatorAssignment1",
    OPERATOR_ASSIGNMENT_F: "operatorAssignmentF",
    INCREMENTOR_VAR_1_1: "incremenVar11",
    INCREMENTOR_VAR: "incremenVar",
    DECREMENTOR_VAR_1_1: "decremenVar11",
    DECREMENTOR_VAR: "decremenVar",
    ENTITIES_UNION: "entitiesUnion",
    LAMBDA_EXPRES_BODY_DEF: "lambdaExpressionBodyDefiner",
    GENERIC_1: "generic1",
    GENERIC_2: "generic2",
    GENERIC_F: "genericF",
    COLOR_CODE_HEX_1: "colorCodeHex1",
    COLOR_CODE_HEX_2: "colorCodeHex2",
    COLOR_CODE_HEX_3: "colorCodeHex3",
    COLOR_CODE_HEX_RGB_SIMPLE: "colorCodeHexRGBSimple",
    COLOR_CODE_HEX_RGBA_SIMPLE: "colorCodeHexRGBASimple",
    COLOR_CODE_HEX_4: "colorCodeHex4",
    COLOR_CODE_HEX_RGB_DOUBLE: "colorCodeHexRGBDouble",
    COLOR_CODE_HEX_5: "colorCodeHex5",
    COLOR_CODE_HEX_RGBA_DOUBLE: "colorCodeHexRGBADouble",
    COMMENT_ONE_LINE_F: "commentOneLineF",
    COMMENT_MULTILINE: "commentMultiline",
    COMMENT_MULTILINE_1: "commentMultiline1",
    COMMENT_MULTILINE_F: "commentMultilineF",
    CHARACTER: "caracter",
    CHARACTER_1: "caracter1",
    CHARACTER_F: "caracterF",
    INDEX: "index",
    INDEX_F: "indexF",
    INDEX_1: "index1",
    INDEX_2: "index2"
};

export const isColorCodeHexState = STATE => (
    [
        STATES.COLOR_CODE_HEX_1,
        STATES.COLOR_CODE_HEX_2,
        STATES.COLOR_CODE_HEX_3,
        STATES.COLOR_CODE_HEX_RGB_SIMPLE,
        STATES.COLOR_CODE_HEX_RGBA_SIMPLE,
        STATES.COLOR_CODE_HEX_4,
        STATES.COLOR_CODE_HEX_RGB_DOUBLE,
        STATES.COLOR_CODE_HEX_5,
        STATES.COLOR_CODE_HEX_RGBA_DOUBLE,
    ].includes(STATE)
);