export const STATES = {
    START: "start",
    INTEGER: "integer",
    IDENTIFIER: "identifier",
    OPERATOR_PLUS: "operatorPlus",
    OPERATOR_SUBTRACTION: "operatorSubtraction",
    OPERATOR_DIVISION: "operatorDivision",
    OPERATOR_PRODUCT: "operatorProduct",
    OPERATOR_POWER: "operatorPower",
    OPERATOR_MODULE: "operatorModule",
    START_PAREN: "startParen",
    END_PAREN: "endParen",
    START_CURLY_BRACE: "startCurlyBrace",
    END_CURLY_BRACE: "endCurlyBrace",
    OPERATOR_CONJ_1: "operatorConj1",
    OPERATOR_CONJ_F: "operatorConjF",
    OPERATOR_DISJ_1: "operatorDisj1",
    OPERATOR_DISJ_F: "operatorDisjF",
    OPERATOR_NOT: "operatorNot",
    DECREMENTOR_VAR_1_1: "decrementorVar11",
    DECREMENTOR_VAR: "decrementorVar",
    MULTIPLIER_VAR: "multiplierVar",
    OPERATOR_GREATER_THAN: "operatorGreaterThan",
    OPERATOR_GREATER_THAN_OR_EQUAL_TO : "operatorGreaterThanOrEqualTo",
    OPERATOR_LESS_THAN: "operatorLessThan",
    OPERATOR_LESS_THAN_OR_EQUAL_TO : "operatorLessThanOrEqualTo",
    STRING_1: "string1",
    STRING_INTERP_1: "stringInterpolation1",
    STRING_INTERP_2: "stringInterpolation2",
    STRING_F: "stringF",
    EOF: "end",
    RESERVED_WORD: "reservedWord",
    ERROR: "error",
    OPERATOR_ASSIGNMENT_1: "operatorAssignment1",
    OPERATOR_ASSIGNMENT_F: "operatorAssignmentF",
    INCREMENTOR_VAR_1_1: "incremenVar11",
    INCREMENTOR_VAR: "incremenVar",
    DECREMENTOR_VAR_1_1: "decremenVar11",
    DECREMENTOR_VAR: "decremenVar",
    ENTITIES_UNION: "entitiesUnion",
    LAMBDA_EXPRES_BODY_DEF_1: "lambdaExpressionBodyDefiner1",
    LAMBDA_EXPRES_BODY_DEF_F: "lambdaExpressionBodyDefinerF",
    GENERIC_1: "generic1",
    GENERIC_F: "genericF",
    // Código hexadecimal de color
    COLOR_CODE_HEX_1: "colorCodeHex1"
};