export const STATES = {
    START: "start",
    INTEGER: "integer",
    IDENTIFIER: "identifier",
    OPERATOR_PLUS: "operatorPlus",
    OPERATOR_DIVISION: "operatorDivision",
    OPERATOR_PRODUCT: "operatorProduct",
    START_PAREN: "startParen",
    OPERATOR_CONJ_1: "operatorConj1",
    OPERATOR_CONJ_F: "operatorConjF",
    OPERATOR_DISJ_1: "operatorDisj1",
    OPERATOR_DISJ_F: "operatorDisjF",
    OPERATOR_NOT: "operatorNot",
    DECREMENTOR_VAR_1_1: "decrementorVar11",
    DECREMENTOR_VAR: "decrementorVar",
    MULTIPLIER_VAR: "multiplierVar",
    OPERATOR_GREATER_THAN: "operatorGreaterThan",
    END_PAREN: "endParen",
    STRING_1: "string1",
    STRING_F: "stringF",
    STRING_INTERP_1: "stringInterpolation1",
    STRING_INTERP_2: "stringInterpolation2",
    STRING_INTERP_F: "stringInterpolationF",
    EOF: "end",
    RESERVED_WORD: "reservedWord",
    ERROR: "error"
};