import { STATES } from "./states";
import { CHARACTER_LIST } from "./characters";
/*
             |    letra       |digito       |     _
---------------------------------------------------------------
inicio       |  identificador |    entero     | identificador
identificador|  identificador | identificador | identificador
entero       |  identificador |    entero     | error
*/

export const TRANSITION_DIAGRAM = {
    [STATES.START]: {
        [CHARACTER_LIST.LETTER]: STATES.IDENTIFIER,
        [CHARACTER_LIST.UNDERSCORE]: STATES.IDENTIFIER,
        [CHARACTER_LIST.DIGIT]: STATES.INTEGER,
        [CHARACTER_LIST.ASTERISK]: STATES.OPERATOR_PRODUCT,
        [CHARACTER_LIST.SLASH]: STATES.OPERATOR_DIVISION,
        [CHARACTER_LIST.PLUS]: STATES.OPERATOR_PLUS,
        [CHARACTER_LIST.HYPHEN]: STATES.OPERATOR_PLUS,
        [CHARACTER_LIST.SEMICOLON]: STATES.EOF,
        [CHARACTER_LIST.START_PAREN]: STATES.START_PAREN,
        [CHARACTER_LIST.END_PAREN]: STATES.END_PAREN,
        [CHARACTER_LIST.AMPERSAND]: STATES.OPERATOR_CONJ_1,
        [CHARACTER_LIST.VERTICAL_BAR]: STATES.OPERATOR_DISJ_1,
        [CHARACTER_LIST.EXCLAMATION_MARK]: STATES.OPERATOR_NOT
    },
    [STATES.INTEGER]: {
        [CHARACTER_LIST.DIGIT]: STATES.INTEGER
    },
    [STATES.IDENTIFIER]: {
        [CHARACTER_LIST.LETTER]: STATES.IDENTIFIER,
        [CHARACTER_LIST.UNDERSCORE]: STATES.IDENTIFIER,
        [CHARACTER_LIST.DIGIT]: STATES.IDENTIFIER
    },
    [STATES.OPERATOR_CONJ_1]: {
        [CHARACTER_LIST.AMPERSAND]: STATES.OPERATOR_CONJ_F
    },
    [STATES.OPERATOR_CONJ_F]: {},
    [STATES.OPERATOR_DISJ_1]: {
        [CHARACTER_LIST.VERTICAL_BAR]: STATES.OPERATOR_DISJ_F
    },
    [STATES.OPERATOR_DISJ_F]: {},
    [STATES.OPERATOR_NOT]: {},
    [STATES.OPERATOR_PLUS]: {},
    [STATES.OPERATOR_PRODUCT]: {},
    [STATES.OPERATOR_DIVISION]: {},
    [STATES.EOF]: {},
    [STATES.START_PAREN]: {},
    [STATES.END_PAREN]: {}
};